[workspace]
resolver = "2"
members = [
    "sdk",
    "connectors/hello-world",
    "connectors/k8s-mini",
    "connectors/prometheus",
    "connectors/k8s",
    "connectors/jaeger",
    "connectors/k8s-events",
    "connectors/flagd",
    "connectors/code-repo",
    "handlers/scale-deploy",
    "handlers/k8s-handler",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["SRE Graph Team"]

[workspace.dependencies]
wit-bindgen = "0.58"
# wasm32-wasip2 有完整 libstd,不需要 no_std + alloc。Phase 1 直接吃标准 serde。
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"
module-sdk  = { path = "sdk" }

[profile.release]
opt-level = "s"   # size first — WASM 模块越小启动越快
lto       = true
strip     = true
panic     = "abort"
codegen-units = 1
